export const esquemaTablaConvenios = [
    { name: "FECHA", type: "datetime" },
    { name: "ID_CONVENIO", type: "int" },
    { name: "EAN", type: "varchar", maxLength: 20 },
    { name: "MATERIAL", type: "varchar", maxLength: 18 },
    { name: "DESCRIPCION", type: "varchar", maxLength: 40 },
    { name: "NIT_PROVEEDOR", type: "varchar", maxLength: 16 },
    { name: "NOMBRE_PROVEEDOR", type: "varchar", maxLength: 60 },
    { name: "GRUPO_ARTICULO", type: "char", maxLength: 9 },
    { name: "CATEGORIA", type: "char", maxLength: 4 },
    { name: "SUBCATEGORIA", type: "char", maxLength: 4 },
    { name: "GRUPO_TERAPEUTICO", type: "varchar", maxLength: 25 },
    { name: "PRINCIPIO_ACTIVO", type: "varchar", maxLength: 25 },
    { name: "GRUPO_COMPRAS", type: "varchar", maxLength: 30 },
    { name: "FECHA_INICIAL", type: "datetime" },
    { name: "FECHA_FINAL", type: "datetime" },
    { name: "PERIODO_LIQUIDACION", type: "varchar", maxLength: 20 },
    { name: "TIPO_ROTACION", type: "varchar", maxLength: 20 },
    { name: "CONTEMPLACIONES", type: "varchar", maxLength: 60 },
    { name: "CLASIFICACION", type: "varchar", maxLength: 4 },
    { name: "PCJ_REBATE_BACORDE", type: "numeric" },
    { name: "PCJ_REBATE_COM_TRIM", type: "numeric" },
    { name: "PCJ_REBATE_MANEJO_LINEA", type: "numeric" },
    { name: "PCJ_REBATE_ROTACION", type: "numeric" },
    { name: "PCJ_REBATE_INFO", type: "numeric" },
    { name: "PCJ_REBATE_NO_DEV", type: "numeric" },
    { name: "PCJ_REBATE_DIN_COM", type: "numeric" },
    { name: "PCJ_REBATE_DIAS_INV", type: "numeric" },
    { name: "PCJ_REBATE_IMPACTOS", type: "numeric" },
    { name: "PCJ_REBATE_AVERIAS", type: "numeric" },
    { name: "PCJ_REBATE_LOGISTICA", type: "numeric" },
    { name: "OBJETIVO_IMPACTOS_Q1", type: "money" },
    { name: "OBJETIVO_COMPRAS", type: "money" },
    { name: "OBJ_MANEJO_LINEA", type: "varchar", maxLength: 30 },
    { name: "OBJ_IMPACTOS_Q4", type: "money" },
    { name: "OBJ_COMPRAS_Q1", type: "money" },
    { name: "OBJ_COMPRAS_Q2", type: "money" },
    { name: "OBJ_COMPRAS_Q4", type: "money" },
    { name: "OBJ_ROTACION_Q1", type: "money" },
    { name: "OBJ_ROTACION_Q2", type: "money" },
    { name: "OBJ_ROTACION_Q3", type: "money" },
    { name: "OBJ_ROTACION_Q4", type: "money" }
];


export const esquemaTablaInventarios = [
    { name: "OFICINA_VENTAS", type: "char", maxLength: 4 },
    { name: "FECHA", type: "datetime" },
    { name: "DIA", type: "int" },
    { name: "MES", type: "int" },
    { name: "ANIO", type: "int" },
    { name: "EAN", type: "varchar", maxLength: 20 },
    { name: "MATERIAL", type: "varchar", maxLength: 18 },
    { name: "DESCRIPCION", type: "varchar", maxLength: 40 },
    { name: "LIBRE_UTILIZACION", type: "int" },
    { name: "VLR_LIBRE_UTILIZACION", type: "money" },
    { name: "CENTRO", type: "varchar", maxLength: 4 },
    { name: "NIT_PROVEEDOR", type: "varchar", maxLength: 16 },
    { name: "NOMBRE_PROVEEDOR", type: "varchar", maxLength: 60 },
    { name: "GRUPO_ARTICULO", type: "char", maxLength: 9 },
    { name: "RAPELS", type: "varchar", maxLength: 50 },
    { name: "CATEGORIA", type: "varchar", maxLength: 25 },
    { name: "SUBCATEGORIA", type: "varchar", maxLength: 25 },
    { name: "GRUPO_TERAPEUTICO", type: "varchar", maxLength: 25 },
    { name: "PRINCIPIO_ACTIVO", type: "varchar", maxLength: 25 },
    { name: "UBICACION", type: "varchar", maxLength: 100 },
    { name: "LOTE", type: "varchar", maxLength: 10 },
    { name: "FECHA_VENCIMIENTO", type: "date" },
    { name: "ULTIMA_FECHA_INGRESO", type: "date" },
    { name: "FECHA_ACTUAL", type: "datetime" },
    { name: "TIEMPO_OBSOLESENCIA", type: "int" },
    { name: "EXCLUSIONES", type: "varchar", maxLength: 30 },
    { name: "CATEGORIA_RAPELS", type: "varchar", maxLength: 25 },
    { name: "PROMEDIO_VTAS_UND", type: "int" },
    { name: "PROMEDIO_VTAS_COTOS", type: "int" },
    { name: "PCJ_PART_ROT", type: "decimal" },
    { name: "PCJ_ACUM_ROT", type: "decimal" },
    { name: "DIAS_INVENT", type: "int" },
    { name: "INVENT_OPTIMO_UND", type: "int" },
    { name: "INVENT_OPTIMO_VLRS", type: "int" },
    { name: "EXCESO_UND", type: "int" },
    { name: "EXCESO_VLRS", type: "int" },
    { name: "RANGO", type: "varchar", maxLength: 100 },
    { name: "CLASIFICACION_ROTACION", type: "char", maxLength: 3 },
    { name: "GRUPO_COMPRAS", type: "varchar", maxLength: 25 },
    { name: "NULA_ROTACION", type: "varchar", maxLength: 16 },
    { name: "DIAS_CONVENIOS", type: "int" },
    { name: "CLASIFICACION_REBATE", type: "varchar", maxLength: 20 },
    { name: "POLITICA_DEV", type: "varchar", maxLength: 120 },
    { name: "TIPO_OFERTA", type: "varchar", maxLength: 30 }
];


export const esquemaTablaOrdenesCompras = [
    { name: "FECHA_OC", type: "datetime" },
    { name: "DIA", type: "int" },
    { name: "MES", type: "int" },
    { name: "ANIO", type: "int" },
    { name: "DIA_SEMANA", type: "int" },
    { name: "EAN", type: "varchar", maxLength: 20 },
    { name: "MATERIAL", type: "varchar", maxLength: 18 },
    { name: "DESCRIPCION", type: "varchar", maxLength: 40 },
    { name: "TIPO_PRODUCTO", type: "varchar", maxLength: 20 },
    { name: "NIT_PROVEEDOR", type: "varchar", maxLength: 16 },
    { name: "NOMBRE_PROVEEDOR", type: "varchar", maxLength: 60 },
    { name: "GRUPO_ARTICULO", type: "varchar", maxLength: 255 },
    { name: "CATEGORIA", type: "varchar", maxLength: 20 },
    { name: "GRUPO_TERAPEUTICO", type: "varchar", maxLength: 25 },
    { name: "SUBCATEGORIA", type: "varchar", maxLength: 25 },
    { name: "PRINCIPIO_ACTIVO", type: "varchar", maxLength: 25 },
    { name: "DESCUENTO_COMERCIAL", type: "int" },
    { name: "SUBTOTAL", type: "money" },
    { name: "IVA", type: "int" },
    { name: "RT_FUENTE", type: "int" },
    { name: "ICA", type: "int" },
    { name: "R_IVA", type: "int" },
    { name: "COSTOS_UND", type: "int" },
    { name: "TOTAL_PAGAR", type: "int" },
    { name: "ORGANIZACION", type: "char", maxLength: 4 },
    { name: "CENTRO", type: "int" },
    { name: "GRUPO_COMPRAS", type: "varchar", maxLength: 20 },
    { name: "FAMILIA_PRODUCTO", type: "varchar", maxLength: 20 },
    { name: "UNIDADES_BARCORDER", type: "int" },
    { name: "VLR_BARCORDER", type: "int" }
];


export const esquemaTablaPresupuestoCompras = [
    { name: "OFICINA_VENTAS", type: "char", maxLength: 4 },
    { name: "FECHA", type: "datetime" },
    { name: "DIA", type: "int" },
    { name: "MES", type: "int" },
    { name: "ANIO", type: "int" },
    { name: "DIA_SEMANA", type: "int" },
    { name: "EAN", type: "varchar", maxLength: 20 },
    { name: "MATERIAL", type: "varchar", maxLength: 18 },
    { name: "DESCRIPCION", type: "varchar", maxLength: 40 },
    { name: "FAMILIA_PRODUCTO", type: "varchar", maxLength: 20 },
    { name: "ESTADO_STATUS", type: "varchar", maxLength: 40 },
    { name: "NIT_PROVEEDOR", type: "varchar", maxLength: 16 },
    { name: "NOMBRE_PROVEEDOR", type: "varchar", maxLength: 60 },
    { name: "GRUPO_ARTICULO", type: "varchar", maxLength: 255 },
    { name: "CATEGORIA", type: "char", maxLength: 4 },
    { name: "SUBCATEGORIA", type: "char", maxLength: 4 },
    { name: "GRUPO_TERAPEUTICO", type: "varchar", maxLength: 25 },
    { name: "PRINCIPIO_ACTIVO", type: "varchar", maxLength: 25 },
    { name: "CLASIFICACION_ROTACION", type: "varchar", maxLength: 3 },
    { name: "GRUPO_COMPRAS", type: "varchar", maxLength: 30 },
    { name: "LIBRE_UTILIZACION", type: "int" },
    { name: "VALOR_LIBRE_UTILIZACION", type: "money" },
    { name: "PROMEDIO_ROTACION_UND", type: "int" },
    { name: "PROMEDIO_ROTACION_VLR", type: "money" },
    { name: "VENTA_DIARIA", type: "money" },
    { name: "VENTA_OPTIMA", type: "int" },
    { name: "VLR_PRESUPUESTO", type: "money" },
    { name: "PROMEDIO_VTAS_EVENTOS", type: "money" },
    { name: "PCJ_PARTIC_EVENTO", type: "decimal" },
    { name: "PCJ_PARTIC_MERCADO", type: "decimal" },
    { name: "ESTACIONALIDAD_TEMPORADA", type: "varchar", maxLength: 30 },
    { name: "FRECUENCIA_TELEFERIAS", type: "varchar", maxLength: 30 },
    { name: "FRECUENCIA_EVENTOS", type: "varchar", maxLength: 30 },
    { name: "FRECUENCIA_COMPRAS", type: "varchar", maxLength: 30 },
    { name: "PROMEDIO_IMPACTOS", type: "int" },
    { name: "PROMEDIO_POBLACIONES", type: "int" },
    { name: "ESTIMACION_DEMANDA", type: "varchar", maxLength: 30 },
    { name: "TIPO_OFERTA", type: "varchar", maxLength: 30 }
];

export const esquemaTablaPresupuestoVentas = [
    { name: "BODEGA", type: "varchar", maxLength: 10 },
    { name: "ID_PRESUPUESTO", type: "int" },
    { name: "FECHA_INICIAL", type: "datetime", nullable: true, default: "getdate()" },
    { name: "FECHA_FINAL", type: "datetime", nullable: true, default: "getdate()" },
    { name: "MES", type: "int" },
    { name: "ANIO", type: "int" },
    { name: "PRESUPUESTO_VALOR", type: "money" },
    { name: "CUOTA_IMPACTOS", type: "int" },
    { name: "CUOTA_REFERENCIAS", type: "int" },
    { name: "CUOTA_VOLUMEN", type: "int" },
    { name: "ID_TIPO_PPTO", type: "int" },
    { name: "TIPO_PRESUPUESTO", type: "varchar", maxLength: 30 },
    { name: "PERIOCIDAD", type: "varchar", maxLength: 20 },
    { name: "NIT_CLIENTE", type: "varchar", maxLength: 16 },
    { name: "TIPO_DOCUMENTO", type: "char", maxLength: 2 },
    { name: "CODIGO_SAP", type: "varchar", maxLength: 10 },
    { name: "NOMBRES_CLIENTE", type: "varchar", maxLength: 100 },
    { name: "RAZON_COMERCIAL", type: "varchar", maxLength: 120 },
    { name: "CIUDAD", type: "varchar", maxLength: 40 },
    { name: "DEPARTAMENTO", type: "varchar", maxLength: 40 },
    { name: "NIT_VENDEDOR", type: "varchar", maxLength: 16 },
    { name: "CODIGO_SAP_VENDEDOR", type: "varchar", maxLength: 10 },
    { name: "NOMBRE_VENDEDOR", type: "varchar", maxLength: 100 },
    { name: "TELEVENDEDOR", type: "varchar", maxLength: 10 },
    { name: "CODIGO_ZONA", type: "char", maxLength: 6 },
    { name: "DESCRIPCION_ZONA", type: "varchar", maxLength: 120 },
    { name: "GRUPO1", type: "char", maxLength: 3 },
    { name: "GRUPO2", type: "char", maxLength: 3 },
    { name: "NIT_LABORATORIO", type: "varchar", maxLength: 16 },
    { name: "GRUPO_ARTICULO", type: "char", maxLength: 9 },
    { name: "RAPELS", type: "varchar", maxLength: 50 },
    { name: "NOMBRE_LABORATORIO", type: "varchar", maxLength: 60 },
    { name: "CATEGORIA", type: "char", maxLength: 4 },
    { name: "SUBCATEGORIA", type: "char", maxLength: 4 },
    { name: "GRUPO_TERAPEUTICO", type: "varchar", maxLength: 25 },
    { name: "PRINCIPIO_ACTIVO", type: "varchar", maxLength: 25 }
];


export const esquemaTablaRebate = [
    { name: "BODEGA", type: "varchar", maxLength: 10 },
    { name: "ID_PPTO_REBATE", type: "int" },
    { name: "FECHA_INICIAL", type: "datetime" },
    { name: "FECHA_FINAL", type: "datetime" },
    { name: "MES", type: "int" },
    { name: "ANIO", type: "int" },
    { name: "PRESUPUESTO_VALOR", type: "money" },
    { name: "CUOTA_IMPACTOS", type: "int" },
    { name: "CUOTA_REFERENCIAS", type: "int" },
    { name: "CUOTA_VOLUMEN", type: "int" },
    { name: "ID_TIPO_REBATE", type: "int" },
    { name: "TIPO_PRESUPUESTO_REBATE", type: "varchar", maxLength: 40 },
    { name: "PERIOCIDAD", type: "varchar", maxLength: 20 },
    { name: "PCJ_NOTA_GANAR", type: "decimal" },
    { name: "NIT_CLIENTE", type: "varchar", maxLength: 16 },
    { name: "TIPO_DOCUMENTO", type: "varchar", maxLength: 30 },
    { name: "CODIGO_SAP", type: "varchar", maxLength: 10 },
    { name: "NOMBRES_CLIENTE", type: "varchar", maxLength: 100 },
    { name: "RAZON_COMERCIAL", type: "varchar", maxLength: 120 },
    { name: "CIUDAD", type: "varchar", maxLength: 40 },
    { name: "DEPARTAMENTO", type: "varchar", maxLength: 40 },
    { name: "NIT_VENDEDOR", type: "varchar", maxLength: 16 },
    { name: "CODIGO_SAP_VENDEDOR", type: "varchar", maxLength: 10 },
    { name: "NOMBRE_VENDEDOR", type: "varchar", maxLength: 100 },
    { name: "TELEVENDEDOR", type: "varchar", maxLength: 10 },
    { name: "CODIGO_ZONA", type: "char", maxLength: 6 },
    { name: "DESCRIPCION_ZONA", type: "varchar", maxLength: 120 },
    { name: "GRUPO1", type: "char", maxLength: 3 },
    { name: "GRUPO2", type: "char", maxLength: 3 },
    { name: "NIT_LABORATORIO", type: "varchar", maxLength: 16 },
    { name: "GRUPO_ARTICULO", type: "char", maxLength: 9 },
    { name: "RAPELS", type: "varchar", maxLength: 50 },
    { name: "NOMBRE_LABORATORIO", type: "varchar", maxLength: 60 },
    { name: "CATEGORIA", type: "char", maxLength: 4 },
    { name: "SUBCATEGORIA", type: "char", maxLength: 4 },
    { name: "GRUPO_TERAPEUTICO", type: "varchar", maxLength: 25 },
    { name: "PRINCIPIO_ACTIVO", type: "varchar", maxLength: 25 }
];


export const esquemaTablaVentas = [
    { name: "BODEGA", type: "varchar", maxLength: 10 },
    { name: "FECHA_VTA", type: "datetime" },
    { name: "HORA_PEDIDO", type: "datetime" },
    { name: "HORA_FACTURACION", type: "datetime" },
    { name: "FECHA_DESPACHO", type: "datetime" },
    { name: "ANIO", type: "int" },
    { name: "MES", type: "int" },
    { name: "DIA_SEMANA", type: "varchar", maxLength: 20 },
    { name: "TIPO_DOCUMENTO", type: "char", maxLength: 2 },
    { name: "NUMERO_DOCUMENTO", type: "varchar", maxLength: 16 },
    { name: "DOCUMENTO_REFERENCIA", type: "varchar", maxLength: 16 },
    { name: "MATERIAL", type: "varchar", maxLength: 18 },
    { name: "DESCRIPCION_MATERIAL", type: "varchar", maxLength: 255 },
    { name: "CODIGO_CUM", type: "varchar", maxLength: 20 },
    { name: "TIPO_MATERIAL", type: "char", maxLength: 4 },
    { name: "CANTIDAD", type: "int" },
    { name: "COSTO_UNITARIO", type: "numeric" },
    { name: "COSTO_TOTAL", type: "numeric" },
    { name: "VALOR_UNITARIO", type: "numeric" },
    { name: "TOTAL_VENTA_BRUTA", type: "numeric" },
    { name: "PORCENTAJE_IVA", type: "decimal"},
    { name: "VALOR_IVA", type: "numeric" },
    { name: "DTO1", type: "numeric"},
    { name: "DTO2", type: "numeric"},
    { name: "DTO3", type: "numeric"},
    { name: "VALOR_DCTO", type: "numeric" },
    { name: "VALOR_DCTO_TOTAL", type: "numeric" },
    { name: "VENTA_NETA", type: "numeric" },
    { name: "VALOR_UTILIDAD", type: "decimal" },
    { name: "MARGEN_UTILIDAD", type: "numeric"},
    { name: "TIPO_VENTA", type: "varchar", maxLength: 16 },
    { name: "LISTA_PRECIOS", type: "char", maxLength: 2 },
    { name: "NIT_LABORATORIO", type: "varchar", maxLength: 16 },
    { name: "GRUPO_ARTICULO", type: "char", maxLength: 9 },
    { name: "RAPELS", type: "varchar", maxLength: 50 },
    { name: "NOMBRE_LABORATORIO", type: "varchar", maxLength: 60 },
    { name: "CATEGORIA", type: "char", maxLength: 4 },
    { name: "SUBCATEGORIA", type: "char", maxLength: 4 },
    { name: "GRUPO_TERAPEUTICO", type: "varchar", maxLength: 25 },
    { name: "PRINCIPIO_ACTIVO", type: "varchar", maxLength: 25 },
    { name: "NIT_REAL", type: "varchar", maxLength: 16 },
    { name: "RESPONSABLE_PAGO", type: "varchar", maxLength: 16 },
    { name: "CODIGO_SAP", type: "varchar", maxLength: 10 },
    { name: "NOMBRE_CLIENTE", type: "varchar", maxLength: 100 },
    { name: "RAZON_SOCIAL", type: "varchar", maxLength: 65 },
    { name: "DIRECCION", type: "varchar", maxLength: 60 },
    { name: "BARRIO", type: "varchar", maxLength: 40 },
    { name: "TELEFONO", type: "varchar", maxLength: 30 },
    { name: "ID_CIUDAD", type: "int" },
    { name: "CIUDAD", type: "varchar", maxLength: 40 },
    { name: "ID_DPTO", type: "int" },
    { name: "DEPARTAMENTO", type: "varchar", maxLength: 40 },
    { name: "LATITUD", type: "varchar", maxLength: 30 },
    { name: "LONGITUD", type: "varchar", maxLength: 30 },
    { name: "CODIGO_BRICKS", type: "int" },
    { name: "USUARIO_FACT", type: "varchar", maxLength: 30 },
    { name: "DESCRIPCION_USUARIO_FACT", type: "varchar", maxLength: 255 },
    { name: "NIT_VENDEDOR", type: "varchar", maxLength: 16 },
    { name: "CODIGO_SAP_VENDEDOR", type: "varchar", maxLength: 10 },
    { name: "NOMBRE_VENDEDOR", type: "varchar", maxLength: 100 },
    { name: "CODIGO_ZONA", type: "char", maxLength: 6 },
    { name: "DESCRIPCION_ZONA", type: "varchar", maxLength: 120 },
    { name: "CODIGO_TIPO", type: "int" },
    { name: "TIPO_TERCERO", type: "char", maxLength: 6 },
    { name: "CLASE_PEDIDO", type: "char", maxLength: 6 },
    { name: "DESCRIPCION_CLASE_PEDIDO", type: "varchar", maxLength: 30 },
    { name: "GRUPO_CLIENTES", type: "char", maxLength: 4 },
    { name: "SUBGRUPO_CLIENTES", type: "char", maxLength: 4 },
    { name: "USUARIO_PEDIDO", type: "varchar", maxLength: 10 },
    { name: "EAN", type: "varchar", maxLength: 20 },
    { name: "PLAN_REBATE", type: "varchar", maxLength: 255 },
    { name: "PORCENTAJE_REBATE", type: "numeric" },
    { name: "COORDINADOR_VENTAS", type: "varchar", maxLength: 30 }
];