<?php
include('funciones.php');
conectar();
switch ($_POST['op']) {
	case 'TRAZABILIDAD':
		$sql = "SELECT DISTINCT
					--ORGANIZACION
					CASE P.ORGANIZACION_VENTAS
						WHEN '1000' THEN 'COMERCIALIZADORA MULTIDROGAS S.A.S'
						ELSE 'DISTRIBUIDORA FARMACEUTICA ROMA S.A'
					END AS ORG,
					CASE P.OFICINA_VENTAS
						WHEN '1100' THEN 'MONTERIA - 1100'
						WHEN '1200' THEN 'CARTAGENA - 1200'
						WHEN '2100' THEN 'MEDELLIN - 2100'
						WHEN '2200' THEN 'BOGOTA - 2200'
						WHEN '2300' THEN 'CALI - 2300'
						WHEN '2400' THEN 'BARRANQUILLA - 2400'
					END AS BODEGA,
					--CLIENTE
					T.NOMBRES,
					T.NIT,
					T.RAZON_COMERCIAL,
					T.DEPARTAMENTO,
					T.CIUDAD,
					T.DIRECCION,
					T.CODIGO_SAP,
					--PEDIDO
					P.NUMERO,
					P.USUARIO,
					CAST(CAST(P.FECHA_PEDIDO AS DATE) AS VARCHAR)+' '+CAST(CAST(P.FECHA_PEDIDO AS TIME(0)) AS VARCHAR) AS FECHA_PEDIDO,
					O.USUARIO AS USUARIO_OT,
					O.FECHA_HORA AS FECHA_OT,
					DATEDIFF(MINUTE, P.FECHA_PEDIDO, O.FECHA_HORA) AS DIF_PEDIDO,
					--SEPARACION
					O.NUMERO_OT,
					U.[LOGIN] AS USUARIO_SEPARA,
					CAST(CAST(O.INICIO_PICKING AS DATE) AS VARCHAR)+' '+CAST(CAST(O.INICIO_PICKING AS TIME(0)) AS VARCHAR) AS INI_SEP,
					CAST(CAST(O.FIN_PICKING AS DATE) AS VARCHAR)+' '+CAST(CAST(O.FIN_PICKING AS TIME(0)) AS VARCHAR) AS FIN_SEP,
					DATEDIFF(MINUTE, 
					CAST(CAST(O.INICIO_PICKING AS DATE) AS VARCHAR)+' '+CAST(CAST(O.INICIO_PICKING AS TIME(0)) AS VARCHAR), 
					CAST(CAST(O.FIN_PICKING AS DATE) AS VARCHAR)+' '+CAST(CAST(O.FIN_PICKING AS TIME(0)) AS VARCHAR)) AS DIF_SEPA,
					--FACTURACION
					F.USUARIO AS USUARIO_FACT,
					F.TIPO_FACTURA+' '+F.NUMERO_FACTURA AS NUMERO_FACT,
					CAST(CAST(F.FECHA_INICIO AS DATE) AS VARCHAR)+' '+CAST(CAST(F.HORA_INICIO AS TIME(0)) AS VARCHAR) AS INI_FACT,
					CAST(CAST(F.FECHA_FIN AS DATE) AS VARCHAR)+' '+CAST(CAST(F.HORA_FIN AS TIME(0)) AS VARCHAR) AS FIN_FACT,
					DATEDIFF(MINUTE, 
					CAST(CAST(F.FECHA_INICIO AS DATE) AS VARCHAR)+' '+CAST(CAST(F.HORA_INICIO AS TIME(0)) AS VARCHAR), 
					CAST(CAST(F.FECHA_FIN AS DATE) AS VARCHAR)+' '+CAST(CAST(F.HORA_FIN AS TIME(0)) AS VARCHAR)) AS DIF_FACT,
					--DESPACHO											
					FORMAT(CONVERT(DATETIME, CAST(L.FECHA_INICIO AS VARCHAR)), 'yyyy-MM-dd HH:mm:ss') AS INI_TRANS,
					FORMAT(CONVERT(DATETIME, CAST(L.FECHA_FIN AS VARCHAR)), 'yyyy-MM-dd HH:mm:ss') AS FIN_TRANS,
					DATEDIFF(MINUTE, 
					FORMAT(CONVERT(DATETIME, CAST(L.FECHA_INICIO AS VARCHAR)), 'yyyy-MM-dd HH:mm:ss'), 
					FORMAT(CONVERT(DATETIME, CAST(L.FECHA_FIN AS VARCHAR)), 'yyyy-MM-dd HH:mm:ss')) AS DIF_TRANS,
					CASE 
						WHEN E.TIPO_USUARIO = 'M' THEN (SELECT UPPER(U.NOMBRES+' '+U.APELLIDOS) FROM T_USUARIOS U WHERE U.ID = E.ID_USUARIO)
						ELSE (SELECT UPPER(R.NOMBRES) FROM T_TRANSPORTADORES R WHERE R.ID = E.ID_USUARIO)
					END AS USUARIO_DESP,
					L.ID_LOTE AS ID_TRANSPORTE,
					L.GUIA,
					L.NOTA_ENTREGA,
					--EMPAQUE
					CONVERT(VARCHAR(30),M.FECHA_INICIO,120) AS FINI_EMPAQUE,
					CONVERT(VARCHAR(30),M.FECHA_FIN,120) AS FFIN_EMPAQUE,
					DATEDIFF(MINUTE, 
					CONVERT(VARCHAR(30),M.FECHA_INICIO,120), 
					CONVERT(VARCHAR(30),M.FECHA_FIN,120)) AS DIF_EMPA,
					M.N_BOLSAS,
					M.N_CAJAS,
					M.N_PAQUETES,
					UM.[LOGIN] AS USUARIO_EMPAQUE
				FROM T_PEDIDOS P 
				INNER JOIN T_TERCEROS              T ON T.CODIGO_SAP     = P.CODIGO_SAP
				LEFT  JOIN T_SEPARACION_OT_DETALLE D ON D.PEDIDO        = P.NUMERO 
				LEFT  JOIN T_SEPARACION_OT         O ON D.NUMERO_OT     = O.NUMERO_OT 
				LEFT  JOIN T_USUARIOS              U ON U.ID = O.ID_USR_PICKING
				LEFT  JOIN T_PEDIDOS_FACTURA       F ON F.NUMERO_PEDIDO = P.NUMERO
				LEFT  JOIN T_DESPACHO_LOTE_DET     L ON L.NUMERO_FACTURA = F.NUMERO_FACTURA 
				LEFT  JOIN T_DESPACHO_LOTE         E ON E.ID = L.ID_LOTE 
				LEFT  JOIN T_EMPAQUE               M ON M.NUMERO_FACTURA = F.NUMERO_FACTURA
				LEFT  JOIN T_USUARIOS              UM ON UM.ID = M.ID_USUARIO
				WHERE P.NUMERO = '" . $_POST['numero'] . "'";
	echo json_encode(GenerarArray($sql, ""));
	mssql_close();

	break;
}